### ISSUE TITLE
Online news source copies publication days from print source

### ISSUE THREAD

**Issue by vestedinterests** [opted-eu/wp3inventory#141]
When I add an online news source to an existing print source, and therefore chose "related", I will enter "continous" as the mode of publication for the website, yet it seems to still copy the Monday-Saturday publication rythm over from the related print source. When continious is selected for the online source, this seems like conflicting information, so perhaps the days-field should be voided in the case of continuous publication.

**Comment by mrwunderbar666** [comment]
"founded" also fasly copied
