### ISSUE TITLE
Trim whitespace from numbers

### ISSUE THREAD

**Issue by vestedinterests** [opted-eu/wp3inventory#142]
When users enter the number of visitors to a website or circulation, they might copy the number from a news article, accidently including whitespace at the beginning or end of the number " 1000".s´ I would suggest either clarifying the error of why the entry for the field is invalid or just trimming white space at the beginning and end of number fields.

**Comment by mrwunderbar666** [comment]
This problem is related to the default validation rules of the browser. The javascript handling the step-by-step validation needs to handle optional fields better
