### ISSUE TITLE
Error wipes all information from form

### ISSUE THREAD

**Issue by vestedinterests** [opted-eu/wp3inventory#154]
I tried being cheeky by adding trying to add a channel we don't support "YouTube" (#22); the main issue is however, that when the message 
> Tool could not be added: Error in <channels>! provided value is not a UID: YouTube

is displayed, the entire form is reloaded and empty; meaning that if someone makes a mistake when entering a tool, they have to enter everything again as before. I think the error handling here should be more like news sources, who still keep info in the forms.

**Comment by mrwunderbar666** [comment]
fixed
