### ISSUE TITLE
Fill-in for tools from GitHub

### ISSUE THREAD

**Issue by vestedinterests** [opted-eu/wp3inventory#195]
1. When using the magic-fill-in option for a Github rep, the website throws an error saying no connection to an API could be made, despite nearly all relevant fields being populated correctly.
2. On the other hand, fields that were previously populated (AFAIK), such as assigning "Open Source" and reading the programming language from Github info?, are no longer populated.
(tested on koheiw/newspapers)

**Comment by vestedinterests** [comment]
adding pmyteh/tm.plugin.proquest, and all works as expected

**Comment by mrwunderbar666** [comment]
Error occurs when github repo uses HTML as "programming language". Not available in the field for selection.

```
TypeError: Cannot set properties of null (setting 'selected')
    at fillForm (external_apis.js:179:90)
    at external_apis.js:143:29
handleError @ external_apis.js:216
```

Desired behaviour: if fails to select the value in field, should just skip it, instead of raising an error
